<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.13" />
    <PackageReference Include="Refit" Version="9.0.2" />
    <PackageReference Include="Serilog" Version="4.3.1" />
    <PackageReference Include="TS.EntityFrameworkCore.GenericRepository" Version="9.0.4" />
    <PackageReference Include="TS.MediatR" Version="9.0.6" />
   
  </ItemGroup>

</Project>
